[project]
name      = "aide-codium-extension"
version   = "0.1.0"
channels  = ["conda-forge", "https://software.repos.intel.com/python/conda"]
platforms = ["linux-64"]

[dependencies]
python                = "3.11.*"
ffmpeg                = "*"
qdrant-client         = "*"
pypdf2                = "*"
python-docx           = "*"
tesseract             = "*"
pytesseract           = "*"
pdf2image             = "*"
pillow = ">=11.3.0,<12"
ebooklib              = "*"
markdown              = "*"
requests              = "*"
transformers = ">=4.53.3,<5"
tokenizers            = "*"
numpy                 = "*"
scipy                 = "*"
pysoundfile           = "*"
librosa               = "*"
pyaudio               = "*"
fastapi               = "*"
uvicorn = ">=0.35.0,<0.36"
websockets            = "*"
pydantic              = "*"
watchdog              = "*"
gitpython             = "*"
tqdm                  = "*"
click                 = "*"
rich                  = "*"
webrtcvad             = "*"
llama-cpp-python      = "*"
ctransformers         = "*"
bitsandbytes          = "*"
accelerate = ">=1.9.0,<2"
chromadb              = "*"
dpcpp_cpp_rt          = "*"
"ruamel.yaml"         = "*"
mistral-common = ">=1.8.3,<2"
pytorch = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"
torchaudio = ">=2.7.1,<3"

[pypi-dependencies]
openai-whisper              = "*"
vosk                        = "*"
coqui-tts                   = "*"
google-api-python-client    = "*"
serpapi                     = "*"
duckduckgo-search           = "*"
sentence-transformers       = "*"
loguru                      = "*"
torch                       = "*"
torchvision                 = "*"
torchaudio                  = "*"
intel-extension-for-pytorch = ">=2.7.0, <3"
oneccl-bind-pt              = { version="*", index="https://pytorch-extension.intel.com/release-whl/stable/xpu/us/" }
transformers = "*"
accelerate = "*"
pillow = "*"
mistral-common = "*"

