# ======== Backend and Model Settings ========
host: 127.0.0.1
port: 8000
db_path: ./vectors.db
offline_index_path: ./index/
gpu_device: xpu
model: ./models/

# ======== Online Search Providers ========
# Set which provider to try first (by default: perplexity)
online_search: perplexity

# Ordered fallback search list (tries next if previous fails)
fallback_order:
  - searxng
  - duckduckgo
  - wikipedia
  - wolframalpha
  - open-meteo

# ======== Provider Endpoints and Keys ========

# --- Perplexity AI ---
# Requires an API key for full use via their API.
perplexity_api_key: ""

# --- DuckDuckGo (Instant Answer API) ---
duckduckgo_api_key: ""   # Not required for public use

# --- Wikipedia API ---
wikipedia_api_key: ""    # Not required for public search

# --- Wolfram Alpha (Short Answer API) ---
# Sign up for a free AppID at https://products.wolframalpha.com/api/
wolframalpha_appid: ""

# --- Open-Meteo (Weather API) ---
open_meteo_api_key: ""   # Not required for basic weather queries

# =========== Usage Example ===========
# Users should update only the API key fields and endpoints above,
# depending on their available/free keys and which search providers they want prioritized.

# =========== End of config.yaml ===========

